version: "3.6"

services:
  learningpack:
    image: learningpack
    build:
      context: .
      dockerfile: Files/Dockerfile

    volumes:
      - ./source:/opt/go/src/learningpack
      - ${HOME}/.gitconfig:/home/hello/.gitconfig

    environment:
      - "GOPATH=/opt/go:$GOPATH"
      - "PATH=/opt/go/bin:$PATH"
      - "PROJECT=learningpack"
  
    ports:
      - "2228:22"